#!/usr/bin/env python3
"""
CIT - Cimeika Integrated Tool
Main CLI entry point
"""
import click
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from cit_stabilize import stabilize


@click.group()
def cli():
    """CIT - Cimeika Integrated Tool"""
    pass


cli.add_command(stabilize)


if __name__ == '__main__':
    cli()
